wandb_version: 1

Batch size:
  desc: null
  value: 16
Learning rate:
  desc: null
  value: 0.001
Optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1670326893.766051
    t:
      1:
      - 1
      - 5
      - 30
      - 41
      - 53
      - 55
      - 63
      - 74
      2:
      - 1
      - 5
      - 30
      - 41
      - 53
      - 55
      - 63
      - 74
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
