wandb_version: 1

Batch size:
  desc: null
  value: 3
Epochs:
  desc: null
  value: 2
Learning rate:
  desc: null
  value: 0.01
Optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1670245841.941514
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
